# Author: Alex Goff
# Data Protection Insights - KMS
#
# This template creates the IAM Role that the KMS Read Lambda will assume.

AWSTemplateFormatVersion: '2010-09-09'
Description: "KMS Keys"
Parameters:
  KMSReadLambdaAccount:
    Description: AWS Account number where the KMS Read Lambda is deployed
    Type: String
  KMSReadRoleName:
    Description: Name of the KMS Read Lambda IAM role. Needs to match KMSReadRole IAM Policy
    Default: XA-KMSRead-Role
    Type: String
  KMSReadLambdaRoleName:
    Description: Name of the central AWS Lambda execution role which assumes the Read Lambda IAM role.
    Default: kms-insights/kms-insights-LambdaRoleListGetKMSdata
    Type: String

Resources:
  # KMS Read Lambda IAM Role
  KMSReadRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Short lived workshop.  More granular permissions not needed"
          - id: W28
            reason: "Short lived workshop.  Resources will not be replaced - only torn down and deleted."
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${KMSReadLambdaAccount}:root"
            Action: 
              sts:AssumeRole
            Condition:
              ArnLike:
                aws:PrincipalArn: !Sub "arn:aws:iam::${KMSReadLambdaAccount}:role/${KMSReadLambdaRoleName}"
      Description: This role allows the central KMS Policy Lambda to read the details of the KMS keys in the account
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action: 
                - "kms:ListKeys"
                - "kms:ListAliases"
                Resource: "*"
              - Effect: Allow
                Action:
                - "kms:ListKeyPolicies"
                - "kms:GetKeyPolicy"
                - "kms:ListResourceTags"
                - "kms:DescribeKey"
                Resource: "arn:aws:kms:*:*:key/*"
              - Sid: CloudTrailLookup
                Effect: Allow
                Action:
                - cloudtrail:LookupEvents
                Resource: '*'

      RoleName: !Ref KMSReadRoleName

